version: "3.8"

services:
  customknowledgebot:
    name: customknowledgebot
    build: .
    ports:
      - "6000:6000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ["python", "main.py"]
