services:
  revisbali-telegram-bot:
    container_name: revisbali-telegram-bot
    build: .
    ports:
      - "6000:6000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - /home/iltoga/revisbali/telegrambot/knowledge_base:/app/knowledge_base
    command: ["python", "main.py"]
    restart: unless-stopped
    networks:
      - dockernet

networks:
  dockernet:
    external: true
