services:
  revisbali-telegram-bot:
    container_name: revisbali-telegram-bot
    build: .
    ports:
      - "6000:6000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ["python", "main.py"]
